// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8DUD_2b0QnVrTSTLlYvPwOv4dsqlA7s',
    appId: '1:964911777240:web:e3909451a8243021dd9ead',
    messagingSenderId: '964911777240',
    projectId: 'olshop-c4d17',
    authDomain: 'olshop-c4d17.firebaseapp.com',
    storageBucket: 'olshop-c4d17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlKxDPnuTdMEy0VfXmAMJOaVPWlqw44I',
    appId: '1:964911777240:android:5e8dc75494d1f06edd9ead',
    messagingSenderId: '964911777240',
    projectId: 'olshop-c4d17',
    storageBucket: 'olshop-c4d17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR8qBRibSIoXHG7O0ZcSMzOlcIzH4Nk0g',
    appId: '1:964911777240:ios:c95f26e653410160dd9ead',
    messagingSenderId: '964911777240',
    projectId: 'olshop-c4d17',
    storageBucket: 'olshop-c4d17.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );
}
